/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.advancedjava.inventorymanagement;

import com.advancedjava.invetorymanagement.httpappache.HttpCallActions;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.HttpClientBuilder;
import org.apache.hc.core5.http.HttpResponse;
import org.apache.hc.core5.http.ParseException;

/**
 *
 * @author Cedric
 */
public class Produit extends javax.swing.JFrame {

    /**
     * Creates new form Slash
     */
    public Produit() throws ParseException {
        initComponents();
        getAllProduit();
    }

    private void getAllProduit() throws ParseException {
        String[] Matériel = {"Num produit", "Designation", "Stock"};
        String[] Ajouter = new String[4];
        DefaultTableModel model = new DefaultTableModel(null, Matériel);
        String endpoint = "/produit";
        CloseableHttpClient httpClient = HttpClientBuilder.create().build();
        JsonArray responseData = HttpCallActions.GET(endpoint, HttpCallActions.getNonSSLClient());

        if (responseData != null) {
            System.out.println("Response Data: " + responseData);

            // Iterate over the elements in the JsonArray
            for (JsonElement element : responseData) {
                if (element.isJsonObject()) {
                    JsonObject jsonObject = element.getAsJsonObject();

                    // Access the properties of each object in the JsonArray
                    String numProduit = jsonObject.get("numProduit").getAsString();
                    String designation = jsonObject.get("design").getAsString();
                    int stock = jsonObject.get("stock").getAsInt();

                    // Process the retrieved data as needed
                    System.out.println("Num produit: " + numProduit);
                    System.out.println("Designation: " + designation);
                    System.out.println("Stock: " + stock);

                    // Add the data to your table model or perform other operations
                    model.addRow(new Object[]{numProduit, designation, stock});
                }
            }
            jTable1.setModel(model);
        } else {
            System.out.println("No response data received.");
        }
    }

    private void searchProduit(String query) throws ParseException {
        String[] Matériel = {"Num produit", "Designation", "Stock"};
        DefaultTableModel model = new DefaultTableModel(null, Matériel);
        String endpoint = "/search";
        CloseableHttpClient httpClient = HttpClientBuilder.create().build();
        JsonArray responseData = HttpCallActions.SEARCH(endpoint, query, HttpCallActions.getNonSSLClient());

        if (responseData != null) {
            System.out.println("Response Data: " + responseData);

            // Iterate over the elements in the JsonArray
            for (JsonElement element : responseData) {
                if (element.isJsonObject()) {
                    JsonObject jsonObject = element.getAsJsonObject();

                    // Access the properties of each object in the JsonArray
                    String numProduit = jsonObject.get("numProduit").getAsString();
                    String designation = jsonObject.get("design").getAsString();
                    int stock = jsonObject.get("stock").getAsInt();

                    // Process the retrieved data as needed
                    System.out.println("Num produit: " + numProduit);
                    System.out.println("Designation: " + designation);
                    System.out.println("Stock: " + stock);

                    // Add the data to your table model or perform other operations
                    model.addRow(new Object[]{numProduit, designation, stock});
                }
            }
        } else {
            System.out.println("No response data received.");
            // Clear the table model
            model.setRowCount(0);
        }

        // Set the table model
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidebarPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MenuContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        num_pro_update_txt = new javax.swing.JTextField();
        designation_update_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        stock_update_txt = new javax.swing.JTextField();
        maj_btn1 = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        recherche_produit_txt = new javax.swing.JTextField();
        recherche_opt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mouvement_btn = new javax.swing.JButton();
        etat_de_stock_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidebarPanel.setBackground(new java.awt.Color(0, 0, 86));
        SidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        SidebarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 10));

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Invigo");
        SidebarPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 30));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cedric\\Documents\\NetBeansProjects\\inventoryManagement\\src\\main\\java\\com\\advancedjava\\inventorymanagement\\assets\\img_maximize.png")); // NOI18N
        jLabel4.setText("Bon de sortie");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        SidebarPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cedric\\Documents\\NetBeansProjects\\inventoryManagement\\src\\main\\java\\com\\advancedjava\\inventorymanagement\\assets\\img_product.png")); // NOI18N
        jLabel6.setText("Produits");
        jLabel6.setToolTipText("");
        SidebarPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cedric\\Documents\\NetBeansProjects\\inventoryManagement\\src\\main\\java\\com\\advancedjava\\inventorymanagement\\assets\\img_minimize.png")); // NOI18N
        jLabel7.setText("Bon de entrée");
        jLabel7.setToolTipText("");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel7KeyPressed(evt);
            }
        });
        SidebarPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        getContentPane().add(SidebarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 510));

        MenuContent.setBackground(new java.awt.Color(255, 255, 255));
        MenuContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cedric\\Documents\\NetBeansProjects\\inventoryManagement\\src\\main\\java\\com\\advancedjava\\inventorymanagement\\assets\\img_add.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        MenuContent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, 50));

        jLabel5.setBackground(new java.awt.Color(0, 0, 86));
        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 86));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Produits");
        MenuContent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        MenuContent.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        MenuContent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 420, 320));

        jPanel1.setBackground(new java.awt.Color(0, 0, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 86));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Panneau de modification");
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 50));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Numéro :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 40));

        num_pro_update_txt.setBackground(new java.awt.Color(255, 255, 255));
        num_pro_update_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                num_pro_update_txtMouseReleased(evt);
            }
        });
        num_pro_update_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_pro_update_txtActionPerformed(evt);
            }
        });
        jPanel1.add(num_pro_update_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, 40));

        designation_update_txt.setBackground(new java.awt.Color(255, 255, 255));
        designation_update_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designation_update_txtActionPerformed(evt);
            }
        });
        jPanel1.add(designation_update_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Désignation :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Stock :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 40));

        stock_update_txt.setBackground(new java.awt.Color(255, 255, 255));
        stock_update_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_update_txtActionPerformed(evt);
            }
        });
        jPanel1.add(stock_update_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, 40));

        maj_btn1.setBackground(new java.awt.Color(255, 255, 255));
        maj_btn1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        maj_btn1.setForeground(new java.awt.Color(0, 0, 86));
        maj_btn1.setText("Modifier");
        maj_btn1.setContentAreaFilled(false);
        maj_btn1.setOpaque(true);
        maj_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maj_btn1MouseClicked(evt);
            }
        });
        maj_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maj_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(maj_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, 40));

        delete_btn.setBackground(new java.awt.Color(255, 255, 255));
        delete_btn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(0, 0, 86));
        delete_btn.setText("Supprimer");
        delete_btn.setContentAreaFilled(false);
        delete_btn.setOpaque(true);
        delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_btnMouseClicked(evt);
            }
        });
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 100, 40));

        MenuContent.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 220, 330));

        recherche_produit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_produit_txtActionPerformed(evt);
            }
        });
        recherche_produit_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recherche_produit_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recherche_produit_txtKeyTyped(evt);
            }
        });
        MenuContent.add(recherche_produit_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, 40));

        recherche_opt.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        recherche_opt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numéro", "Désignation" }));
        recherche_opt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_optActionPerformed(evt);
            }
        });
        MenuContent.add(recherche_opt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 100, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Liste des produits actuellement en stock chez Invigo.");
        MenuContent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jButton1.setText("Rechercher");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuContent.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, 40));

        mouvement_btn.setBackground(new java.awt.Color(255, 255, 255));
        mouvement_btn.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        mouvement_btn.setForeground(new java.awt.Color(0, 0, 86));
        mouvement_btn.setText("MOUVEMENT DE STOCK");
        mouvement_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouvement_btnMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mouvement_btnMouseReleased(evt);
            }
        });
        mouvement_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouvement_btnActionPerformed(evt);
            }
        });
        MenuContent.add(mouvement_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 220, 30));

        etat_de_stock_btn.setBackground(new java.awt.Color(255, 255, 255));
        etat_de_stock_btn.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        etat_de_stock_btn.setForeground(new java.awt.Color(0, 0, 86));
        etat_de_stock_btn.setText("ETAT DE STOCK");
        etat_de_stock_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etat_de_stock_btnMouseClicked(evt);
            }
        });
        etat_de_stock_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etat_de_stock_btnActionPerformed(evt);
            }
        });
        MenuContent.add(etat_de_stock_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 220, 30));

        getContentPane().add(MenuContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 760, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num_pro_update_txtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_pro_update_txtMouseReleased

    }//GEN-LAST:event_num_pro_update_txtMouseReleased

    private void num_pro_update_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_pro_update_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_pro_update_txtActionPerformed

    private void designation_update_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designation_update_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designation_update_txtActionPerformed

    private void stock_update_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_update_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_update_txtActionPerformed

    private void maj_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maj_btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maj_btn1MouseClicked

    private void maj_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maj_btn1ActionPerformed
        String id = (jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0)).toString();

        try {
            String endpoint = "/produit/" + id;
            String jsonBody = "{\n"
                    + "    \"numProd\": \"" + num_pro_update_txt.getText() + "\",\n"
                    + "    \"design\": \"" + designation_update_txt.getText() + "\",\n"
                    + "    \"stock\": \"" + stock_update_txt.getText() + "\"\n"
                    + "}";

            // Call the request
            HttpCallActions.PUT(endpoint, jsonBody, HttpCallActions.getNonSSLClient());
            JOptionPane.showMessageDialog(null, "Produit mis à jour !");
            getAllProduit();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_maj_btn1ActionPerformed

    private void delete_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_btnMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Êtes vous sûr de vouloir supprimer ce produit ?", "Confirmation", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.YES_OPTION) {
            String id = (jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0)).toString();
            try {
                String endpoint = "/produit/" + id;

                // Call the request
                HttpCallActions.DELETE(endpoint, null, HttpCallActions.getNonSSLClient());
                JOptionPane.showMessageDialog(null, "Produit supprimé !");
                getAllProduit();

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            // User clicked "No" button or closed the dialog
            // Do nothing or handle accordingly
        }
    }//GEN-LAST:event_delete_btnMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

    }//GEN-LAST:event_delete_btnActionPerformed

    private void recherche_produit_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_produit_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherche_produit_txtActionPerformed

    private void recherche_produit_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recherche_produit_txtKeyReleased

    }//GEN-LAST:event_recherche_produit_txtKeyReleased

    private void recherche_produit_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recherche_produit_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_recherche_produit_txtKeyTyped

    private void recherche_optActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_optActionPerformed

    }//GEN-LAST:event_recherche_optActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int i = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        num_pro_update_txt.setText(model.getValueAt(i, 0).toString());
        designation_update_txt.setText(model.getValueAt(i, 1).toString());
        stock_update_txt.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_jTable1MouseReleased

    private void jLabel7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel7KeyPressed
        Produit.super.dispose();
        BonEntree bonEntree = null;
        try {
            bonEntree = new BonEntree();
        } catch (ParseException ex) {
            Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
        }
        bonEntree.setVisible(true);
    }//GEN-LAST:event_jLabel7KeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Produit.super.dispose();
        BonEntree bonEntree = null;
        try {
            bonEntree = new BonEntree();
        } catch (ParseException ex) {
            Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
        }
        bonEntree.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Produit.super.dispose();
        BonSortie bonSortie = null;
        try {
            bonSortie = new BonSortie();
        } catch (ParseException ex) {
            Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
        }
        bonSortie.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        AjouterProduit ajoutProduit = new AjouterProduit();
        ajoutProduit.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String recherche_opt_value = (String) recherche_opt.getSelectedItem();
        if (recherche_opt_value == "Numéro") {
            try {
                searchProduit("numProduit" + recherche_produit_txt.getText());
            } catch (ParseException ex) {
                Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (recherche_opt_value == "Désignation") {
            try {
                searchProduit("design" + recherche_produit_txt.getText());
            } catch (ParseException ex) {
                Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void mouvement_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouvement_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mouvement_btnActionPerformed

    private void etat_de_stock_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etat_de_stock_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etat_de_stock_btnActionPerformed

    private void etat_de_stock_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etat_de_stock_btnMouseClicked
        Produit.super.dispose();
        EtatStock etatStock = null;
        try {
            etatStock = new EtatStock();
        } catch (ParseException ex) {
            Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
        }
        etatStock.setVisible(true);
    }//GEN-LAST:event_etat_de_stock_btnMouseClicked

    private void mouvement_btnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouvement_btnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_mouvement_btnMouseReleased

    private void mouvement_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouvement_btnMouseClicked
        Produit.super.dispose();
        MouvementStock mouvementStock = null;
        try {
            mouvementStock = new MouvementStock();
        } catch (ParseException ex) {
            Logger.getLogger(Produit.class.getName()).log(Level.SEVERE, null, ex);
        }
        mouvementStock.setVisible(true);
    }//GEN-LAST:event_mouvement_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Produit().setVisible(true);

                } catch (ParseException ex) {
                    Logger.getLogger(Produit.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuContent;
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField designation_update_txt;
    private javax.swing.JButton etat_de_stock_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton maj_btn1;
    private javax.swing.JButton mouvement_btn;
    private javax.swing.JTextField num_pro_update_txt;
    private javax.swing.JComboBox<String> recherche_opt;
    private javax.swing.JTextField recherche_produit_txt;
    private javax.swing.JTextField stock_update_txt;
    // End of variables declaration//GEN-END:variables
}
